version: '2.1'

services:

  spotifycontrol:
    build: .
    restart: unless-stopped
    ports:
      - "5005:5005"
    volumes:
      - ./config/config.json:/spotifycontrol/config/config.json
    network_mode: "host"
